version: '3.8'

services:
  supervisor:
    build:
      context: .
      dockerfile: containers/Dockerfile.python
    volumes:
      - ./:/workspace
      - ./config.lmstudio.toml:/workspace/config.toml
      - dependencies:/openhands
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"  # Main API endpoint
    environment:
      - OPENHANDS_CONFIG=/workspace/config.toml
      - OPENHANDS_AGENT=SupervisorAgent
    command: >
      bash -c "cd /workspace/frontend && 
      npm install && 
      npm run build && 
      cd /workspace && 
      python -m uvicorn openhands.server.listen:app --host 0.0.0.0 --port 8000"
    networks:
      - openhands-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 4G

  openhands-1:
    build:
      context: .
      dockerfile: containers/Dockerfile.python
    volumes:
      - ./:/workspace
      - ./config.lmstudio.toml:/workspace/config.toml
      - dependencies:/openhands
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OPENHANDS_CONFIG=/workspace/config.toml
      - OPENHANDS_AGENT=OpenHandsAgent-1
    command: ["python", "-m", "uvicorn", "openhands.server.listen:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    networks:
      - openhands-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 4G

  openhands-2:
    build:
      context: .
      dockerfile: containers/Dockerfile.python
    volumes:
      - ./:/workspace
      - ./config.lmstudio.toml:/workspace/config.toml
      - dependencies:/openhands
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OPENHANDS_CONFIG=/workspace/config.toml
      - OPENHANDS_AGENT=OpenHandsAgent-2
    command: ["python", "-m", "uvicorn", "openhands.server.listen:app", "--host", "0.0.0.0", "--port", "8002"]
    ports:
      - "8002:8002"
    networks:
      - openhands-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  openhands-net:
    driver: bridge

volumes:
  dependencies:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker_volumes/dependencies
      o: bind

